site_name: lib-bpmn-engine
site_url: https://nitram509.github.io/lib-bpmn-engine/

theme: material

repo_url: https://github.com/nitram509/lib-bpmn-engine

#lang: en

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Advanced Examples:
      - 'Microservice & REST API': advanced-microservice.md
      - 'Zeebe Exporter (visualization)': advanced-zeebe.md
      - 'Timers & schedulers': advanced-timers.md
  - Supported Elements: supported-elements.md
  - Expression Syntax: expression-syntax.md
  - Roadmap: roadmap.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

#plugins:
#  - social
